/**
 * CrewPay Ledger Level 1.5 Phase 1 helpers.
 *
 * Workbook remains the source of truth. These helpers only read/write workbook
 * tabs and do not send email, create calendar events, call APIs, or bridge apps.
 */

const SHEETS = Object.freeze({
  WORKER_PROOF: 'Worker Proof',
  WORKERS: 'Workers',
  PAY_PERIODS: 'Pay Periods',
  TIME_ENTRIES: 'Time Entries',
  PROOF_EXPORTS: 'Proof Exports',
  ACCESS_LOG: 'Access Log',
  CORRECTION_LOG: 'Correction Log',
  ADMIN_NOTICES: 'Admin Notices',
});

const PROOF_CELLS = Object.freeze({
  WORKER_ID: 'B3',
  PAY_PERIOD_ID: 'B4',
  GENERATED_AT: 'B9',
  SELECTOR_CHECK: 'B10',
});

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('CrewPay Ledger')
    .addItem('Generate Worker Proof', 'generateWorkerProof')
    .addItem('Log Proof Export', 'logProofExport')
    .addItem('Log Access Change', 'logAccessChange')
    .addItem('Log Correction', 'logCorrection')
    .addItem('Create Email-Ready Notice', 'createEmailReadyNotice')
    .addSeparator()
    .addItem('About CrewPay Ledger', 'aboutCrewPayLedger')
    .addToUi();
}

function generateWorkerProof() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const proofSheet = requireSheet_(ss, SHEETS.WORKER_PROOF);
  const workerId = String(proofSheet.getRange(PROOF_CELLS.WORKER_ID).getValue()).trim();
  const payPeriodId = String(proofSheet.getRange(PROOF_CELLS.PAY_PERIOD_ID).getValue()).trim();

  if (!workerId || !payPeriodId) {
    showAlert_('Select a Worker ID and Pay Period ID on Worker Proof before generating proof.');
    return;
  }

  const payPeriod = findRowByValue_(requireSheet_(ss, SHEETS.PAY_PERIODS), 'Pay Period ID', payPeriodId);
  if (!payPeriod) {
    showAlert_(`Pay Period ID not found: ${payPeriodId}`);
    return;
  }

  if (String(payPeriod.record['Worker ID']).trim() !== workerId) {
    proofSheet.getRange(PROOF_CELLS.SELECTOR_CHECK).setValue('CHECK SELECTION - pay period belongs to another worker');
    showAlert_('Worker Proof was not refreshed because the selected pay period belongs to another worker.');
    return;
  }

  proofSheet.getRange(PROOF_CELLS.GENERATED_AT).setValue(new Date());
  proofSheet.getRange(PROOF_CELLS.SELECTOR_CHECK).setValue('OK - worker/pay period match');
  SpreadsheetApp.flush();
  showAlert_('Worker Proof refreshed for the selected worker and pay period only.');
}

function logProofExport() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const proofSheet = requireSheet_(ss, SHEETS.WORKER_PROOF);
  const workerId = String(proofSheet.getRange(PROOF_CELLS.WORKER_ID).getValue()).trim();
  const payPeriodId = String(proofSheet.getRange(PROOF_CELLS.PAY_PERIOD_ID).getValue()).trim();

  assertWorkerPayPeriodMatch_(ss, workerId, payPeriodId);

  const worker = findRowByValue_(requireSheet_(ss, SHEETS.WORKERS), 'Worker ID', workerId);
  const exportType = promptRequired_('Log Proof Export', 'Export Type (Print, PDF, or CSV):', 'Print');
  const exportReference = promptRequired_('Log Proof Export', 'Export Reference:', 'Manual workbook proof');
  const notes = promptOptional_('Log Proof Export', 'Notes:', 'Worker-specific proof only.');

  appendRecord_(requireSheet_(ss, SHEETS.PROOF_EXPORTS), {
    'Export ID': nextId_('X', requireSheet_(ss, SHEETS.PROOF_EXPORTS), 'Export ID'),
    'Worker ID': workerId,
    'Worker Name': worker.record['Worker Name'],
    'Pay Period ID': payPeriodId,
    'Export Type': exportType,
    'Generated At': new Date(),
    'Generated By': currentUser_(),
    'Export Reference': exportReference,
    'Notes': notes,
  });

  showAlert_('Proof export logged for the selected worker only.');
}

function logAccessChange() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const workersSheet = requireSheet_(ss, SHEETS.WORKERS);
  const workerId = promptRequired_('Log Access Change', 'Worker ID:', '');
  const worker = findRowByValue_(workersSheet, 'Worker ID', workerId);
  if (!worker) throwFriendly_(`Worker ID not found: ${workerId}`);

  const previousStatus = String(worker.record['Access Status'] || '').trim();
  const newStatus = promptRequired_('Log Access Change', 'New Status (Active or Inactive):', previousStatus);
  const reason = promptRequired_('Log Access Change', 'Reason:', 'Manual access status update');

  appendRecord_(requireSheet_(ss, SHEETS.ACCESS_LOG), {
    'Log ID': nextId_('A', requireSheet_(ss, SHEETS.ACCESS_LOG), 'Log ID'),
    'Worker ID': workerId,
    'Worker Name': worker.record['Worker Name'],
    'Previous Status': previousStatus,
    'New Status': newStatus,
    'Changed At': new Date(),
    'Changed By': currentUser_(),
    'Reason': reason,
  });

  const headers = headerMap_(workersSheet);
  workersSheet.getRange(worker.rowNumber, headers['Access Status']).setValue(newStatus);
  if (newStatus === 'Inactive' && headers['Inactive At']) {
    workersSheet.getRange(worker.rowNumber, headers['Inactive At']).setValue(new Date());
  }

  showAlert_('Access change logged. Historical records and worker proof remain in the workbook.');
}

function logCorrection() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const entryId = promptRequired_('Log Correction', 'Entry ID:', '');
  const entry = findRowByValue_(requireSheet_(ss, SHEETS.TIME_ENTRIES), 'Entry ID', entryId);
  if (!entry) throwFriendly_(`Entry ID not found: ${entryId}`);

  const payPeriodId = promptRequired_('Log Correction', 'Related Pay Period ID:', '');
  const reason = promptRequired_('Log Correction', 'Correction Reason:', '');
  const originalSummary = promptRequired_('Log Correction', 'Original Value Summary:', '');
  const newSummary = promptRequired_('Log Correction', 'New Value Summary:', '');
  const notes = promptOptional_('Log Correction', 'Notes:', 'Correction logged before changing proof records.');

  appendRecord_(requireSheet_(ss, SHEETS.CORRECTION_LOG), {
    'Correction ID': nextId_('C', requireSheet_(ss, SHEETS.CORRECTION_LOG), 'Correction ID'),
    'Entry ID': entryId,
    'Worker ID': entry.record['Worker ID'],
    'Worker Name': entry.record['Worker Name'],
    'Pay Period ID': payPeriodId,
    'Correction Date': new Date(),
    'Corrected By': currentUser_(),
    'Correction Reason': reason,
    'Original Value Summary': originalSummary,
    'New Value Summary': newSummary,
    'Notes': notes,
  });

  showAlert_('Correction logged. Make any workbook edit visibly, with this correction record retained.');
}

function createEmailReadyNotice() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = requireSheet_(ss, SHEETS.ADMIN_NOTICES);
  const active = sheet.getActiveRange();
  const rowNumber = active ? active.getRow() : 0;
  if (rowNumber < 2) {
    showAlert_('Select a notice row on Admin Notices before creating email-ready text.');
    return;
  }

  const record = recordFromRow_(sheet, rowNumber);
  const workerContext = record['Worker Name'] ? `Worker: ${record['Worker Name']}\n` : '';
  const payPeriodContext = record['Related Pay Period ID'] ? `Pay Period: ${record['Related Pay Period ID']}\n` : '';
  const noticeText = [
    `Subject: ${record.Subject || ''}`,
    '',
    workerContext + payPeriodContext + String(record.Message || ''),
    '',
    'Note: This is email-ready text only. This helper does not send email.',
  ].join('\n');

  const headers = headerMap_(sheet);
  if (headers['Delivery Method']) sheet.getRange(rowNumber, headers['Delivery Method']).setValue('Email Ready');
  if (headers['Notice Status']) sheet.getRange(rowNumber, headers['Notice Status']).setValue('Posted');
  if (headers.Notes) {
    const prior = String(sheet.getRange(rowNumber, headers.Notes).getValue() || '');
    sheet.getRange(rowNumber, headers.Notes).setValue(`${prior ? prior + '\n\n' : ''}${noticeText}`);
  }

  showAlert_(noticeText);
}

function aboutCrewPayLedger() {
  showAlert_(
    'CrewPay Ledger Phase 1 helpers only refresh proof, write logs, and create email-ready notice text. ' +
      'The workbook remains the source of truth. No email sending, calendar sync, backend, database, or app bridge is included.'
  );
}

function requireSheet_(ss, name) {
  const sheet = ss.getSheetByName(name);
  if (!sheet) throwFriendly_(`Required sheet missing: ${name}`);
  return sheet;
}

function headerMap_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  const map = {};
  headers.forEach((header, index) => {
    if (header) map[String(header).trim()] = index + 1;
  });
  return map;
}

function recordFromRow_(sheet, rowNumber) {
  const headers = headerMap_(sheet);
  const values = sheet.getRange(rowNumber, 1, 1, sheet.getLastColumn()).getValues()[0];
  const record = {};
  Object.keys(headers).forEach((header) => {
    record[header] = values[headers[header] - 1];
  });
  return record;
}

function findRowByValue_(sheet, headerName, value) {
  const headers = headerMap_(sheet);
  if (!headers[headerName]) throwFriendly_(`Required header missing on ${sheet.getName()}: ${headerName}`);
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return null;
  const values = sheet.getRange(2, headers[headerName], lastRow - 1, 1).getValues();
  const needle = String(value).trim();
  for (let i = 0; i < values.length; i += 1) {
    if (String(values[i][0]).trim() === needle) {
      const rowNumber = i + 2;
      return { rowNumber, record: recordFromRow_(sheet, rowNumber) };
    }
  }
  return null;
}

function appendRecord_(sheet, record) {
  const headers = headerMap_(sheet);
  const row = Object.keys(headers).map((header) => (header in record ? record[header] : ''));
  sheet.appendRow(row);
}

function nextId_(prefix, sheet, idHeader) {
  const headers = headerMap_(sheet);
  if (!headers[idHeader]) throwFriendly_(`Required header missing on ${sheet.getName()}: ${idHeader}`);
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return `${prefix}-0001`;
  const values = sheet.getRange(2, headers[idHeader], lastRow - 1, 1).getValues().flat();
  let max = 0;
  values.forEach((value) => {
    const match = String(value).match(/(\d+)$/);
    if (match) max = Math.max(max, Number(match[1]));
  });
  return `${prefix}-${String(max + 1).padStart(4, '0')}`;
}

function assertWorkerPayPeriodMatch_(ss, workerId, payPeriodId) {
  if (!workerId || !payPeriodId) throwFriendly_('Worker ID and Pay Period ID are required.');
  const worker = findRowByValue_(requireSheet_(ss, SHEETS.WORKERS), 'Worker ID', workerId);
  if (!worker) throwFriendly_(`Worker ID not found: ${workerId}`);
  const payPeriod = findRowByValue_(requireSheet_(ss, SHEETS.PAY_PERIODS), 'Pay Period ID', payPeriodId);
  if (!payPeriod) throwFriendly_(`Pay Period ID not found: ${payPeriodId}`);
  if (String(payPeriod.record['Worker ID']).trim() !== workerId) {
    throwFriendly_('Selected pay period belongs to a different worker. Worker-specific proof was not logged.');
  }
  return { worker, payPeriod };
}

function promptRequired_(title, prompt, defaultValue) {
  const response = SpreadsheetApp.getUi().prompt(title, prompt, SpreadsheetApp.getUi().ButtonSet.OK_CANCEL);
  if (response.getSelectedButton() !== SpreadsheetApp.getUi().Button.OK) throwFriendly_('Action canceled.');
  const value = String(response.getResponseText() || defaultValue || '').trim();
  if (!value) throwFriendly_('A value is required.');
  return value;
}

function promptOptional_(title, prompt, defaultValue) {
  const response = SpreadsheetApp.getUi().prompt(title, prompt, SpreadsheetApp.getUi().ButtonSet.OK_CANCEL);
  if (response.getSelectedButton() !== SpreadsheetApp.getUi().Button.OK) throwFriendly_('Action canceled.');
  return String(response.getResponseText() || defaultValue || '').trim();
}

function currentUser_() {
  const email = Session.getActiveUser().getEmail();
  return email || 'Workbook User';
}

function showAlert_(message) {
  SpreadsheetApp.getUi().alert(String(message));
}

function throwFriendly_(message) {
  SpreadsheetApp.getUi().alert(String(message));
  throw new Error(message);
}
